name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'
      
      - name: Install dependencies
        run: npm install
        
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: storybook-static
          build_command: npm run build-storybook