name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'
          
      - name: Install dependencies
        run: npm install

      - name: Publish deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
          build_command: npm run build-storybook
          install_command: npm run deploy-storybook